language: c++

sudo: required
dist: trusty #xenial

compiler:
  - gcc
  - clang

env: 
  - V8_VERSION=5.9
  - V8_VERSION=6.0
#  - V8_VERSION=6.4

before_install:
  - sudo add-apt-repository ppa:pinepain/libv8-archived -y
#  - sudo add-apt-repository ppa:pinepain/libv8 -y
  - sudo apt-get update -q
  - sudo apt-get install libv8-"$V8_VERSION"-dev -y

install:
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-stdlib=libstdc++"; fi
  
script: make

after_success: LD_LIBRARY_PATH=.:/opt/libv8-${V8_VERSION}/lib ./v8pp_test -v --run-tests test/console.js test/file.js
