language: c++

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:pinepain/v8 -y
  - sudo apt-get update -q
  - sudo apt-get install libv8-dev -y

install:
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-stdlib=libstdc++"; fi
  
script: make

after_success: LD_LIBRARY_PATH=. ./v8pp_test -v --run-tests test/console.js test/file.js
